version: '3.3'

services:
  template-service:
    image: template-service
    container_name: template-service
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    volumes:
      - "./data:/microservice/data"
    networks:
      - template

  template-db:
    image: postgres:alpine
    container_name: template-db
    restart: always
    environment:
      POSTGRES_USER: template
      POSTGRES_PASSWORD: template
      POSTGRES_DB: template
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - template

networks:
  template:
    external: true